---
- name: Deploy
  hosts: green
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    application: green
  become: yes
  tasks:
    - name: Install and deploy docker
      include_role: 
        name: docker
