---

- name: Create EC2 instances
  ec2:
    key_name: pipeline
    instance_type: t2.micro
    image: ami-0a91cd140a1fc148a
    region: us-east-2
    group_id: 
      - sg-076007dfdb9d1006a
      - sg-f4cf3188
#    instance_profile_name: EC2-Ansible
    wait: yes
    instance_tags:
      Name: devops-server-blue
      application: "{{ application }}"
    exact_count: 1
    count_tag:
      application: "{{ application }}"
  register: ec2_instances

- debug: var=ec2_instances
