---
- name: Provision
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    application: blue
  tasks:
    - name: create instances
      include_role: 
        name: create_instance
